using Stocky.Api.Dtos;

namespace Stocky.Api.Services;

/// <summary>
/// M9 advanced-analytics provider surface — bars for charting and
/// analyst-rating consensus / price targets. Real-provider implementations
/// (Finnhub / Polygon) would slot in alongside the deterministic stub.
/// </summary>
public interface IAdvancedMarketDataProvider
{
    /// <summary>
    /// Daily OHLCV bars for a single symbol between <paramref name="from"/>
    /// and <paramref name="to"/> inclusive (used by charts).
    /// </summary>
    Task<IReadOnlyList<OhlcBarDto>> GetOhlcAsync(string symbol, DateOnly from, DateOnly to, CancellationToken ct = default);

    /// <summary>
    /// Analyst-rating consensus + price-target distribution for a symbol.
    /// </summary>
    Task<AnalystRatingDto> GetAnalystRatingAsync(string symbol, CancellationToken ct = default);
}

/// <summary>
/// Deterministic stub for <see cref="IAdvancedMarketDataProvider"/>. Bars are
/// generated by a per-symbol random walk seeded on Hash(symbol) so refresh
/// keeps prices stable across calls; analyst ratings are derived from a
/// price-anchored consensus.
/// </summary>
public sealed class StubAdvancedMarketDataProvider(IMarketDataProvider quotes) : IAdvancedMarketDataProvider
{
    public async Task<IReadOnlyList<OhlcBarDto>> GetOhlcAsync(string symbol, DateOnly from, DateOnly to, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(symbol)) return Array.Empty<OhlcBarDto>();
        if (to < from) (from, to) = (to, from);
        symbol = symbol.ToUpperInvariant();

        // Anchor the walk on the current spot so the chart's last point lines
        // up with whatever quote the user sees on the rest of the UI.
        var quoteList = await quotes.GetQuotesAsync(new[] { symbol }, ct);
        var spot = quoteList.Count > 0 ? quoteList[0].Price : 50m + (Hash(symbol) % 400);
        if (spot <= 0) spot = 50m;

        var totalDays = to.DayNumber - from.DayNumber + 1;
        var bars = new List<OhlcBarDto>(totalDays);
        var rng = new Random(Hash(symbol));

        // Walk backwards from spot so the last bar = today's close.
        var dates = new List<DateOnly>(totalDays);
        for (var d = from; d <= to; d = d.AddDays(1))
        {
            if (d.DayOfWeek == DayOfWeek.Saturday || d.DayOfWeek == DayOfWeek.Sunday) continue;
            dates.Add(d);
        }
        if (dates.Count == 0) return Array.Empty<OhlcBarDto>();

        var closes = new decimal[dates.Count];
        closes[^1] = spot;
        for (var i = dates.Count - 2; i >= 0; i--)
        {
            // Mean-reverting random walk, daily drift ±1.5% capped.
            var drift = (decimal)((rng.NextDouble() - 0.5) * 0.03);
            var prev = closes[i + 1];
            var c = prev / (1 + drift);
            if (c < 1m) c = 1m;
            closes[i] = Math.Round(c, 2);
        }

        for (var i = 0; i < dates.Count; i++)
        {
            var c = closes[i];
            var open = i == 0 ? c : closes[i - 1];
            var hiOffset = (decimal)(rng.NextDouble() * 0.015);
            var loOffset = (decimal)(rng.NextDouble() * 0.015);
            var high = Math.Max(open, c) * (1 + hiOffset);
            var low = Math.Min(open, c) * (1 - loOffset);
            var volume = 500_000L + (long)(rng.NextDouble() * 50_000_000);
            bars.Add(new OhlcBarDto(
                dates[i],
                Math.Round(open, 2),
                Math.Round(high, 2),
                Math.Round(low, 2),
                c,
                volume));
        }
        return bars;
    }

    public async Task<AnalystRatingDto> GetAnalystRatingAsync(string symbol, CancellationToken ct = default)
    {
        symbol = (symbol ?? string.Empty).ToUpperInvariant();
        var quoteList = await quotes.GetQuotesAsync(new[] { symbol }, ct);
        var spot = quoteList.Count > 0 ? quoteList[0].Price : 50m + (Hash(symbol) % 400);
        if (spot <= 0) spot = 50m;

        var rng = new Random(Hash(symbol));
        var strongBuy = rng.Next(2, 16);
        var buy = rng.Next(3, 22);
        var hold = rng.Next(2, 18);
        var sell = rng.Next(0, 7);
        var strongSell = rng.Next(0, 4);
        var total = strongBuy + buy + hold + sell + strongSell;

        // Score on the canonical 1..5 scale (5 = Strong Buy).
        decimal weighted = strongBuy * 5m + buy * 4m + hold * 3m + sell * 2m + strongSell * 1m;
        var score = total > 0 ? Math.Round(weighted / total, 2) : 3m;
        var label = score switch
        {
            >= 4.5m => "Strong Buy",
            >= 3.75m => "Buy",
            >= 2.5m => "Hold",
            >= 1.5m => "Sell",
            _ => "Strong Sell"
        };

        // Price targets centred on a bullish-but-noisy multiple of spot.
        var mean = Math.Round(spot * (1m + (decimal)(rng.NextDouble() * 0.25 + 0.05)), 2);
        var low = Math.Round(spot * (decimal)(rng.NextDouble() * 0.2 + 0.7), 2);
        var high = Math.Round(spot * (decimal)(rng.NextDouble() * 0.35 + 1.2), 2);
        if (low > mean) low = Math.Round(mean * 0.85m, 2);
        if (high < mean) high = Math.Round(mean * 1.15m, 2);
        var median = Math.Round((mean + (low + high) / 2m) / 2m, 2);

        return new AnalystRatingDto(
            symbol,
            score,
            label,
            low,
            mean,
            high,
            median,
            total,
            DateOnly.FromDateTime(DateTime.UtcNow),
            new AnalystRatingDistributionDto(strongBuy, buy, hold, sell, strongSell));
    }

    private static int Hash(string s)
    {
        var h = 0;
        foreach (var c in s) h = unchecked(h * 31 + c);
        return Math.Abs(h);
    }
}
